import type { Event } from '../types';

export const MOCK_EVENTS: Event[] = [
  {
    _id: 'ev1',
    name: 'Aurora Gala 2026',
    venue: 'Grand Ballroom',
    date: 'Sat, Aug 15',
    status: 'live',
    guestCount: 200,
    guestRsvp: 186,
    ticketsSold: 186,
    ticketsTotal: 200,
    seatedCount: 116,
    seatedTotal: 140,
    vendorCount: 12,
    commCount: 3,
  },
  {
    _id: 'ev2',
    name: 'Pella Night',
    venue: 'Riverside Terrace',
    date: 'Fri, Sep 5',
    status: 'planning',
    guestCount: 150,
    guestRsvp: 74,
    ticketsSold: 98,
    ticketsTotal: 150,
    seatedCount: 68,
    seatedTotal: 150,
    vendorCount: 7,
    commCount: 0,
  },
  {
    _id: 'ev3',
    name: 'Zulu Days Festival',
    venue: 'Open Grounds',
    date: 'Sat, Oct 11',
    status: 'draft',
    guestCount: 800,
    guestRsvp: 0,
    ticketsSold: 0,
    ticketsTotal: 800,
    seatedCount: 96,
    seatedTotal: 800,
    vendorCount: 3,
    commCount: 0,
  },
  {
    _id: 'ev4',
    name: 'Lumen Conf',
    venue: 'Metro Convention',
    date: 'Mon, Nov 3',
    status: 'confirmed',
    guestCount: 500,
    guestRsvp: 412,
    ticketsSold: 468,
    ticketsTotal: 500,
    seatedCount: 335,
    seatedTotal: 500,
    vendorCount: 18,
    commCount: 1,
  },
];

export const STATS = {
  activeEvents: 4,
  totalGuests: 672,
  ticketsSold: 752,
  openComms: 4,
};
